### ISSUE TITLE
Error with twisted module when using all commands

### ISSUE THREAD

**Issue by DragoSpiro98** [gsand/mark2#117]
I followed the guide but I have always this error. I'm using Ubuntu with python 2.7.17 and pip3 (as instruction says)

> Traceback (most recent call last):
>   File "/usr/bin/mark2", line 3, in <module>
>     from mk2.launcher import main
>   File "/usr/mark2/mk2/launcher.py", line 14, in <module>
>     from . import manager
>   File "/usr/mark2/mk2/manager.py", line 5, in <module>
>     from twisted.internet import reactor
> ImportError: No module named twisted.internet

**Comment by mattboy9921** [comment]
Just encountered this when trying to set up Mark2 with the latest install instructions. I installed `python-pip` instead of `python-pip3` and used the command `sudo pip install -r requirements.txt` within the `mark2` folder. After that, it works as expected. Not sure why pip3 is an issue here, but that's how I fixed it.

**Comment by Column01** [comment]
Alright, this should have been fixed with my changes to the documentation, but if it wasn't I've since updated mark2 to python 3 and it should no longer be a problem if you reinstall following the install guide. Please make a new issue if you update and still have issues
