### ISSUE TITLE
1.16 mark2 thinks server has crashed.

### ISSUE THREAD

**Issue by iceypotato** [gsand/mark2#120]
I had a similar issue to #118, but this is for 1.16. I'm running the vanilla server jar from the Minecraft website itself. I set `plugin.monitor.crash-unknown-cmd-message=Unknown or incomplete command.*` and it still does not work.

**Comment by iceypotato** [comment]
I fixed the issue, but now in the console I keep getting `/~mark2CrashCheck` every like 10 seconds.

**Comment by kulned** [comment]
What did you do?

**Comment by Column01** [comment]
You need to configure the message for mark2 as he showed above. The line: `plugin.monitor.crash-unknown-cmd-message=Unknown or incomplete command.*` needs to be configured for the proper message for what an unknown command looks like in the mark2 console. Can you share what the unknown command message is for you @kulned

**Comment by synrg** [comment]
I'm surprised, @iceypotato , you did not manage to make it work with the pattern you report you're using. To be clear, this needs to be in mark2.properties, and needs to match whatever message is being logged.

What appears in the log for me:

```
2020-12-09 08:13:49 | Unknown or incomplete command, see below for error
2020-12-09 08:13:49 | /~mark2CrashCheck~<--[HERE]
```

With output like the above, when I add this to my mark2.properties, then stop mark2, then start the server again, the problem is resolved:

```
plugin.monitor.crash-unknown-cmd-message=Unknown.*command.*
```

I made the pattern sufficiently precise so that it should only match some sort of "Unknown command" message, but sufficiently general so that it should match different variations of the message for different server versions (e.g. both "Unknown command" and "Unknown or imcomplete command" will match). This is working for me with a vanilla 1.16 server. I haven't tested it with other server versions.

**Comment by Column01** [comment]
@synrg Thanks for that regex for the unknown command message, I tested it and it seems to cover all the variations of that message. I've since updated the default regex for mark2 along with the python 3 port. @iceypotato if you are still having issues, please update your mark2 install (full reinstall probably is needed) and make a new issue if the issue persists.

**Comment by synrg** [comment]
Hmm. So I just started a new server instance on vanilla 1.18 (still using the setting I came up with above) and just like @iceypotato (I think) it doesn't detect a crash, but it *does* annoyingly output `/~mark2CrashCheck~<--[HERE]` every minute. That never happened with paper. Is there any way to silence that with a vanilla server?

**Comment by Column01** [comment]
Unfortunately no, Vanilla changed to printing the unknown command message in two lines which broke the blocking of the crash alert message. I've been meaning to add something to stop it but its a low priority

**Comment by synrg** [comment]
Ugh. OK ... this is just temporary until the downstreams catch up with 1.18 just released today, so ... I can live with it temporarily. :) Thanks for the speedy answer.
