### ISSUE TITLE
.restarttime command

### ISSUE THREAD

**Issue by SirWilli** [gsand/mark2#36]
would be great if there is a command to see the time left until the next server restart.

**Comment by gsand** [comment]
That would be very tricky because there are multiple ways to initiate mark2 restarts that don't specify a set time the server will restart or call the ~restart command at the very last moment.

So the only way to tell there's going to be a restart would be if the ~restart procedures have already been initiated.

**Example**:
In mark2 console: 
`~restart 24h,30m;15m;5m;1m;30s;15s;10s;5s;4s;3s;2s;1s`.

In `scripts.txt` file:
` * 0 * * * ~restart-empty`
` * 0 * * * ~restart 1m;30s;15s;10s;5s;4s;3s;2s;1s`
