### ISSUE TITLE
~backup is giving "cowardly refusing to create an empty archive"

### ISSUE THREAD

**Issue by TomLewis** [gsand/mark2#48]
After putting in the settings for my backup to be made, im getting:
    cowardly refusing to create an empty archive

the backup folder is created but no tar is being created.

```
###
# BACKUP
# Compresses the world folders to a .tar.gz
# Provides ~backup command
plugin.backup.enabled=true
plugin.backup.path=backups/{timestamp}.tar.gz

# mode
#   include: back up only the paths in 'spec'
#   exclude: back up everything in the server directory except the paths in 'spec
plugin.backup.mode=include

# Semicolon separated paths to include or exclude, depending on mode
plugin.backup.spec=hub

# Flags to pass to `tar`
plugin.backup.tar-flags=-hpczf

# How long to wait after issuing `save-off` for minecraft to finish writing chunks (seconds)
plugin.backup.flush-wait=5
```

**Comment by gsand** [comment]
Hey, sorry for the late response.

I'm honestly considering removing the backup functionality. There are better backup scripts available online, and simple tar backups will eventually get too big or take too long.

I'd recommend rsync. I've also been recommended duplicity and it's wrapper duply.

**Comment by FrozenBeard** [comment]
@gsand any tutorials you can link me to? Its good being part of the wrapper as you could (I haven't been able to get it to work) work in tune with reboots etc, all managed from one place.

**Comment by gsand** [comment]
@gsand any tutorials you can link me to? Its good being part of the wrapper as you could (I haven't been able to get it to work) work in tune with reboots etc, all managed from one place.

@FrozenBeard How about a plugin that allows you to specify system commands to run, but only through the console. That way, you can have mark2 control when backups are done while they're being handled by fully fleshed out backup scripts.

It would work just like the trigger command, but instead of ingame -> ingame response, it would be mark2 console -> system command.

**Comment by FrozenBeard** [comment]
Having system commands run via the console would be handy, if a tested backup script was available and shared on github to be updated by everyone, a shared backup script for spigot would be very handy (maybe one already exists?) I know there was a thread on reddit.com/r/admincraft a while back where people shared their backup scripts.

To add on to this, I have been trying to find a way to trigger a world replace after something happens in-game. Idea being I have a massive pre-made world that players can play on in a game, destroy the crap out of it, and when the game ends it runs a command, which could be passed to the wrapper, which then runs some system commands to re-copy over a pre-saved version of the world over the destroyed one. I assume the world would have to be unloaded or the server shut down first for this to happen but im sure it could be worked into mark2 using commands & console as suggested.

**Comment by gsand** [comment]
That's another feature that I'm planning to add ingame trigger -> mark2 command.

>>anything<<    ---->  ~restart

in the scripts.txt file, you would have

    @serverstopped $redeploy.sh

which would just replace the world directory with an basic template.

**Comment by FrozenBeard** [comment]
That would be fantastic, that would then allow me to run a command from any plugin at the end of a game (I presume) which could then kick all players to a Hub, shut that server down, redeploy the backup of the world from a save via the .sh and restart the server, maybe from the shell script.

**Comment by gsand** [comment]
Not really necessary, it would be better to just have bungeecord move everyone to the lobby on disconnect without a bukkit plugin.

**Comment by FrozenBeard** [comment]
Any feedback on the backup? I recently got a brand new server and need to pick a wrapper, but Im going to need working backups...

**Comment by MeltedLux** [comment]
mark2 backups are working fine on my end.

**Comment by FrozenBeard** [comment]
For some reason it didnt work on my VPS, after moving to a dedicated and setting everything up from scratch its working, takes a whopping 8 minutes to backup 1 world, and gzip using insane CPU. 
How can I set the backups to only create 10 backups before it starts removing the old ones? I can't see this in the config.

**Comment by MeltedLux** [comment]
Use cron and a little bash to to do it:

```ls -t | sed -e '1,10d' | xargs -d '\n' rm```

**Comment by FrozenBeard** [comment]
@MeltedLux awesome, I've decided on writing my own bash backup script, as I want it to work with worldedit snapshops too (zips), then I can throw in odd site backup too.
I don't suppose you have something I could base my script off do you? I assume its possible to send commands to the mark2 servers via the shell? Like save-all and then save-off for the backup...

**Comment by MeltedLux** [comment]
Nope, I just use the built in backup plugin which tar's and moves the archive to an sshfs and then have that small snippet above running every 7 days to remove the last 25 backups.

**Comment by FrozenBeard** [comment]
Alright, I made a pretty good backup script that Zips folders into a structure wordledit can use for //restore, times how long it all takes, logs everything and sends me a pushbullet on completion, I might change it so that it only sends a pushbullet when something fails. 

So the question now is, will we have the possibility to run shell scripts from within game? After playing with bash for the first time, the options are now endless, if we could use the wrapper to send a command to the OS we could automate a lot.

**Comment by gsand** [comment]
I really want to add that feature, but... I'm not sure if people wont misuse it. I'll look into it.

**Comment by FrozenBeard** [comment]
@gsand You can already run OS level commands via the schedule right? If they can misuse it there, then it wont matter about in-game, unless you mean that first time users wont understand it and end up wrecking their system, sounds like something I would do.
Could be toggled off by default, and have the settings explain what it is, and what its for, then its just for high level users.
- Playing a one-time game, the game ends runs ~sendcommand startnewgame.sh from any game plugin
- startnewgame.sh then kicks them all to the hub, shuts down the world/server, Disables teleporting to the world/server, deletes that old world that got destroyed, copys over backup ready for next round, start the server up again, this then can even send commands into the active servers to tell people its all ready for the next round!

All that requires is being able to send a command form in-game to run a server OS command.

**Comment by Column01** [comment]
Your initial error was due to a configuration issue. That will happen when tar doesn't get anything to create an archive with meaning your included paths were wrong as mark2 would run the backup from the root of the server directory. So TL;DR unless you had a folder in the root of the server called `hub`, there's your issue.

You could have used: `../hub` if you wanted to backup the entire server folder and specified a path outside the server directory for the archive like this `plugin.backup.path=../backups/hub/{timestamp}.tar.gz`

As for running shell scripts from in-game, it seems like a major security flaw rather than a feature as we'd really have no way of verifying the person who ran the command was supposed to. Also not sure if it would even work for what you wanted to do (I.E. holding and unholding the server inside a script run by mark2)

Gonna close the issue as the initial problem was fixed

**Comment by TomLewis** [comment]
Initial Issue from 2015, were now i'm 2021 near 2022, I love that you bothered with a reply! I ended up writing my own backup bash script, using zip specifically to use with WorldEdit SnapShots, which lets you select any part of the world to restore from a backup, so 2 birds! 

Something you can learn from this, if you use .zip as an option you get the ability for restoring any parts of the world with WorldEdit:
https://worldedit.enginehub.org/en/latest/usage/snapshots/
