### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by ucraft02** [gsand/mark2#90]
Why I can't save file in utf-9 format???
When I use mark2 is in ANSI if I start server in sreen It work in UTF-8?
Can I change start.sh
I need to start with that

`while true 
do
java -Xmx4000m -Dfile.encoding=UTF-8 -jar Skyblock.jar
echo "Use control + C or it will start again the server."
sleep 5
done`

**Comment by ucraft02** [comment]
I can't change file from ANIS to UTF-8

**Comment by thomas15v** [comment]
Use notepad++, atom, nano, vim, ... . as your editor. In notepad++ you can even convert files to UTF-8. 

(Why do you need [UTF-9](https://en.wikipedia.org/wiki/UTF-9_and_UTF-18) tho?)

**Comment by ucraft02** [comment]
I want to have symbols in some plugins and I convert in utf-8 with notpad++ and when I ~restart server convert it back to ANSI

**Comment by ucraft02** [comment]
Can you tell how can I fixx it to save file in UTF-8??please

**Comment by thomas15v** [comment]
I am not sure what the problem might be. You might wanna rewrite the file using nano(or vim) on the server instead or check out some mods that might do weird stuff (I have seen that before). 

Also you can check the encoding of a file with `file -bi <file_name>`. Validate that the file gets written in the correct encoding and check if the server is converting those.

One thing is sure, this issue is not related to mark2 😉.

**Comment by ucraft02** [comment]
I start server in screen and work with utf-8.Than I start it on mark2 and convert it to ANSI and symbols don't work anymore

**Comment by ucraft02** [comment]
please help

**Comment by gsand** [comment]
Use an editor that allows you to use Unicode line endings.
